// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Triplite_Committee_Platform.Data;

#nullable disable

namespace Triplite_Committee_Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240308192708_CreateBoard")]
    partial class CreateBoard
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RolesModelsUserModel", b =>
                {
                    b.Property<int>("RolesRoleID")
                        .HasColumnType("int");

                    b.Property<int>("UserEmployeeID")
                        .HasColumnType("int");

                    b.HasKey("RolesRoleID", "UserEmployeeID");

                    b.HasIndex("UserEmployeeID");

                    b.ToTable("RolesModelsUserModel");
                });

            modelBuilder.Entity("Triplite_Committee_Platform.Models.BoardModel", b =>
                {
                    b.Property<int>("BoardNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BoardNo"));

                    b.Property<int>("DeptNo")
                        .HasColumnType("int");

                    b.Property<int>("National_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReqDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReqStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReqTypeID")
                        .HasColumnType("int");

                    b.Property<int?>("ScholarshipModelNational_ID")
                        .HasColumnType("int");

                    b.HasKey("BoardNo");

                    b.HasIndex("DeptNo");

                    b.HasIndex("National_ID");

                    b.HasIndex("ReqTypeID");

                    b.HasIndex("ScholarshipModelNational_ID");

                    b.ToTable("Board");
                });

            modelBuilder.Entity("Triplite_Committee_Platform.Models.CollegeModel", b =>
                {
                    b.Property<int>("CollegeNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CollegeNo"));

                    b.Property<string>("CollegeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CollegeNo");

                    b.ToTable("College");
                });

            modelBuilder.Entity("Triplite_Committee_Platform.Models.DepartmentModel", b =>
                {
                    b.Property<int>("DeptNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeptNo"));

                    b.Property<int>("CollegeNo")
                        .HasColumnType("int");

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeptNo");

                    b.HasIndex("CollegeNo");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("Triplite_Committee_Platform.Models.ReasonsModel", b =>
                {
                    b.Property<int>("ReasonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReasonID"));

                    b.Property<bool>("Connected")
                        .HasColumnType("bit");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReqTypeID")
                        .HasColumnType("int");

                    b.HasKey("ReasonID");

                    b.HasIndex("ReqTypeID");

                    b.ToTable("Reasons");
                });

            modelBuilder.Entity("Triplite_Committee_Platform.Models.RequestTypeModel", b =>
                {
                    b.Property<int>("RequestTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestTypeID"));

                    b.Property<string>("RequestTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestTypeID");

                    b.ToTable("RequestType");
                });

            modelBuilder.Entity("Triplite_Committee_Platform.Models.RolesModels", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Triplite_Committee_Platform.Models.ScholarshipModel", b =>
                {
                    b.Property<int>("National_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("National_ID"));

                    b.Property<DateTime>("Beginning_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentStudy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeptNo")
                        .HasColumnType("int");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecificMajor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("University")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("National_ID");

                    b.HasIndex("DeptNo");

                    b.ToTable("Scholarship");
                });

            modelBuilder.Entity("Triplite_Committee_Platform.Models.UserModel", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<int>("DeptNo")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeID");

                    b.HasIndex("DeptNo");

                    b.ToTable("User");
                });

            modelBuilder.Entity("RolesModelsUserModel", b =>
                {
                    b.HasOne("Triplite_Committee_Platform.Models.RolesModels", null)
                        .WithMany()
                        .HasForeignKey("RolesRoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Triplite_Committee_Platform.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserEmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Triplite_Committee_Platform.Models.BoardModel", b =>
                {
                    b.HasOne("Triplite_Committee_Platform.Models.DepartmentModel", "Department")
                        .WithMany("Board")
                        .HasForeignKey("DeptNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Triplite_Committee_Platform.Models.ScholarshipModel", "Scholarship")
                        .WithMany()
                        .HasForeignKey("National_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Triplite_Committee_Platform.Models.RequestTypeModel", "RequestType")
                        .WithMany("Board")
                        .HasForeignKey("ReqTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Triplite_Committee_Platform.Models.ScholarshipModel", null)
                        .WithMany("Board")
                        .HasForeignKey("ScholarshipModelNational_ID");

                    b.Navigation("Department");

                    b.Navigation("RequestType");

                    b.Navigation("Scholarship");
                });

            modelBuilder.Entity("Triplite_Committee_Platform.Models.DepartmentModel", b =>
                {
                    b.HasOne("Triplite_Committee_Platform.Models.CollegeModel", "College")
                        .WithMany("Department")
                        .HasForeignKey("CollegeNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("College");
                });

            modelBuilder.Entity("Triplite_Committee_Platform.Models.ReasonsModel", b =>
                {
                    b.HasOne("Triplite_Committee_Platform.Models.RequestTypeModel", "RequestType")
                        .WithMany("Reasons")
                        .HasForeignKey("ReqTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestType");
                });

            modelBuilder.Entity("Triplite_Committee_Platform.Models.ScholarshipModel", b =>
                {
                    b.HasOne("Triplite_Committee_Platform.Models.DepartmentModel", "Department")
                        .WithMany("Scholarship")
                        .HasForeignKey("DeptNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Triplite_Committee_Platform.Models.UserModel", b =>
                {
                    b.HasOne("Triplite_Committee_Platform.Models.DepartmentModel", "Department")
                        .WithMany()
                        .HasForeignKey("DeptNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Triplite_Committee_Platform.Models.CollegeModel", b =>
                {
                    b.Navigation("Department");
                });

            modelBuilder.Entity("Triplite_Committee_Platform.Models.DepartmentModel", b =>
                {
                    b.Navigation("Board");

                    b.Navigation("Scholarship");
                });

            modelBuilder.Entity("Triplite_Committee_Platform.Models.RequestTypeModel", b =>
                {
                    b.Navigation("Board");

                    b.Navigation("Reasons");
                });

            modelBuilder.Entity("Triplite_Committee_Platform.Models.ScholarshipModel", b =>
                {
                    b.Navigation("Board");
                });
#pragma warning restore 612, 618
        }
    }
}
