// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Triplite_Committee_Platform.Data;

#nullable disable

namespace Triplite_Committee_Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RolesModelsUserModel", b =>
                {
                    b.Property<int>("RolesRoleID")
                        .HasColumnType("int");

                    b.Property<int>("UserEmployeeID")
                        .HasColumnType("int");

                    b.HasKey("RolesRoleID", "UserEmployeeID");

                    b.HasIndex("UserEmployeeID");

                    b.ToTable("RolesModelsUserModel");
                });

            modelBuilder.Entity("Triplite_Committee_Platform.Models.CollegeModel", b =>
                {
                    b.Property<int>("CollegeNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CollegeNo"));

                    b.Property<string>("CollegeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CollegeNo");

                    b.ToTable("College");
                });

            modelBuilder.Entity("Triplite_Committee_Platform.Models.DepartmentModel", b =>
                {
                    b.Property<int>("DeptNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeptNo"));

                    b.Property<int>("CollegeNo")
                        .HasColumnType("int");

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeptNo");

                    b.HasIndex("CollegeNo");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("Triplite_Committee_Platform.Models.RequestType", b =>
                {
                    b.Property<int>("RequestTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestTypeID"));

                    b.Property<string>("RequestTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestTypeID");

                    b.ToTable("RequestType");
                });

            modelBuilder.Entity("Triplite_Committee_Platform.Models.RolesModels", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Triplite_Committee_Platform.Models.ScholarshipModel", b =>
                {
                    b.Property<int>("National_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("National_ID"));

                    b.Property<DateTime>("Beginning_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentStudy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeptNo")
                        .HasColumnType("int");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecificMajor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("University")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("National_ID");

                    b.HasIndex("DeptNo");

                    b.ToTable("Scholarship");
                });

            modelBuilder.Entity("Triplite_Committee_Platform.Models.DepartmentModel", b =>
                {
                    b.HasOne("Triplite_Committee_Platform.Models.CollegeModel", "College")
                        .WithMany("Department")
                        .HasForeignKey("CollegeNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("College");
                });

            modelBuilder.Entity("Triplite_Committee_Platform.Models.ReasonsModel", b =>
                {
                    b.HasOne("Triplite_Committee_Platform.Models.RequestTypeModel", "RequestType")
                        .WithMany("Reasons")
                        .HasForeignKey("ReqTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestType");
                });

            modelBuilder.Entity("Triplite_Committee_Platform.Models.ScholarshipModel", b =>
                {
                    b.HasOne("Triplite_Committee_Platform.Models.DepartmentModel", "Department")
                        .WithMany("Scholarship")
                        .HasForeignKey("DeptNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Triplite_Committee_Platform.Models.CollegeModel", b =>
                {
                    b.Navigation("Department");
                });

            modelBuilder.Entity("Triplite_Committee_Platform.Models.DepartmentModel", b =>
                {
                    b.Navigation("Scholarship");
                });

            modelBuilder.Entity("Triplite_Committee_Platform.Models.RequestTypeModel", b =>
                {
                    b.Navigation("Reasons");
                });
#pragma warning restore 612, 618
        }
    }
}
